source "https://rubygems.org"

gem "highline"
gem "httpclient"
gem "mixlib-config"
gem "mixlib-install"
gem "mixlib-shellout"
gem "train", ">= 2.0.5"

gem "chef", "~> 12.22", ">= 12.22.5"
gem "ohai", "~> 8.26", ">= 8.26.1"

group :development, :test do
  gem "pry"
  gem "rspec"
  gem "rb-readline"
end
